export const PROTOCOL_STATE_IDLE = 0;
export const PROTOCOL_STATE_WAITING_FOR_METADATA = 1;
export const PROTOCOL_STATE_METADATA_RECV = 2;
export const PROTOCOL_STATE_WAITING_FIRST_TOKEN = 3;
export const PROTOCOL_STATE_WAITING_TOKENS = 4;
