export const PROTOCOL_STATE_IDLE = 0;
export const PROTOCOL_STATE_QUEUEING = 1;
export const PROTOCOL_STATE_WAITING_FOR_METADATA = 2;
export const PROTOCOL_STATE_METADATA_RECV = 3;
export const PROTOCOL_STATE_WAITING_FIRST_TOKEN = 4;
export const PROTOCOL_STATE_WAITING_TOKENS = 5;
